CLASS cl_abap_complexdescr DEFINITION
  PUBLIC
  INHERITING FROM cl_abap_datadescr
  ABSTRACT
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.

ENDCLASS.

CLASS cl_abap_complexdescr IMPLEMENTATION.
ENDCLASS.