CLASS cl_xco_dtel_text DEFINITION PUBLIC FINAL CREATE PRIVATE.
  PUBLIC SECTION.
    TYPES:
      list TYPE STANDARD TABLE OF REF TO cl_xco_dtel_text WITH DEFAULT KEY.

ENDCLASS.

CLASS cl_xco_dtel_text IMPLEMENTATION.
ENDCLASS.