CLASS cx_a4c_cp_svc_prop_not_found DEFINITION
  PUBLIC INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_a4c_cp_svc_prop_not_found IMPLEMENTATION.
ENDCLASS.