CLASS cx_a4c_cp_svc_inst_not_exist DEFINITION
  PUBLIC INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_a4c_cp_svc_inst_not_exist IMPLEMENTATION.
ENDCLASS.