CLASS cx_badi_context_error DEFINITION
  PUBLIC
  INHERITING FROM cx_badi
  CREATE PUBLIC.

  PUBLIC SECTION.

    CONSTANTS context_missing TYPE c LENGTH 32 VALUE '5DDA7E44E0AF7C64E10000000A42425B'. "#EC NOTEXT
    CONSTANTS context_not_allowed TYPE c LENGTH 32 VALUE '5EDA7E44E0AF7C64E10000000A42425B'. "#EC NOTEXT
    CONSTANTS cx_badi_context_error TYPE c LENGTH 32 VALUE '5CDA7E44E0AF7C64E10000000A42425B'. "#EC NOTEXT
    DATA badi_name TYPE badi_name.

    METHODS constructor
    IMPORTING
      !textid LIKE textid OPTIONAL
      !previous LIKE previous OPTIONAL
      !badi_name TYPE badi_name OPTIONAL.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_badi_context_error IMPLEMENTATION.
ENDCLASS.