CLASS cx_bcs_mail_config DEFINITION
PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    CONSTANTS:
      BEGIN OF internal_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '000',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF internal_error,

      BEGIN OF config_id_inital,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '001',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF config_id_inital,

      BEGIN OF config_not_found,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '002',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF config_not_found,

      BEGIN OF config_save_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '003',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF config_save_error,

      BEGIN OF hostname_initial,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '004',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF hostname_initial,

      BEGIN OF port_initial,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '005',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF port_initial,

      BEGIN OF smtpauth_not_valid,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '006',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF smtpauth_not_valid,

      BEGIN OF cc_config_not_valid,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '007',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF cc_config_not_valid,

      BEGIN OF default_config_not_found,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '008',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF default_config_not_found,

      BEGIN OF default_not_determinable,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '009',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF default_not_determinable,

      BEGIN OF default_already_exists,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '010',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF default_already_exists,

      BEGIN OF config_delete_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '011',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF config_delete_error,

      BEGIN OF tls_config_not_valid,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '012',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF tls_config_not_valid,

      BEGIN OF password_initial,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '013',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF password_initial,

      BEGIN OF pw_identifier_initial,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '014',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF pw_identifier_initial,

      BEGIN OF cannot_determine_subaccount,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '015',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF cannot_determine_subaccount,

      BEGIN OF function_not_supported,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '016',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF function_not_supported,

      BEGIN OF tenant_domain_initial,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '017',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF tenant_domain_initial,

      BEGIN OF input_value_invalid,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '018',
        attr1 TYPE scx_attrname VALUE 'ATTRIBUTE1',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF input_value_invalid,

      BEGIN OF address_config_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '100',
        attr1 TYPE scx_attrname VALUE 'ATTRIBUTE1',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF address_config_error,

      BEGIN OF recipient_domains_missing,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '101',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF recipient_domains_missing,

      BEGIN OF sender_domains_missing,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '102',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF sender_domains_missing,

      BEGIN OF default_sender_addr_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '110',
        attr1 TYPE scx_attrname VALUE 'ATTRIBUTE1',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF default_sender_addr_error,

      BEGIN OF default_sender_addr_missing,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '111',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF default_sender_addr_missing,

      BEGIN OF recipient_dom_deletion_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '120',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF recipient_dom_deletion_error,

      BEGIN OF sender_dom_deletion_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '121',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF sender_dom_deletion_error,

      BEGIN OF default_sender_deletion_error,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '122',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF default_sender_deletion_error,

      BEGIN OF activate_address_check_failed,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '200',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF activate_address_check_failed,

      BEGIN OF set_expiry_for_mails_failed,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '201',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF set_expiry_for_mails_failed,

      BEGIN OF delete_expiry_for_mails_failed,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '202',
        attr1 TYPE scx_attrname VALUE '',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF delete_expiry_for_mails_failed,

      BEGIN OF non_numeric_parameter,
        msgid TYPE symsgid VALUE 'BCS_MAIL_CONFIG',
        msgno TYPE symsgno VALUE '203',
        attr1 TYPE scx_attrname VALUE 'ATTRIBUTE1',
        attr2 TYPE scx_attrname VALUE '',
        attr3 TYPE scx_attrname VALUE '',
        attr4 TYPE scx_attrname VALUE '',
      END OF non_numeric_parameter.

    DATA:
      attribute1 TYPE string,
      attribute2 TYPE string,
      attribute3 TYPE string,
      attribute4 TYPE string.

    INTERFACES if_t100_dyn_msg.
    INTERFACES if_t100_message.

    METHODS constructor
      IMPORTING
        !textid     LIKE if_t100_message=>t100key OPTIONAL
        !previous   LIKE previous OPTIONAL
        !attribute1 TYPE string OPTIONAL
        !attribute2 TYPE string OPTIONAL
        !attribute3 TYPE string OPTIONAL
        !attribute4 TYPE string OPTIONAL.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_bcs_mail_config IMPLEMENTATION.
ENDCLASS.