CLASS cx_fdt_input DEFINITION
  PUBLIC INHERITING FROM cx_dynamic_check CREATE PUBLIC.

  PUBLIC SECTION.

    CONSTANTS cx_fdt_input TYPE c LENGTH 32 VALUE '00505695007C1EE096AADF1D227B87A7'. "#EC NOTEXT

    METHODS constructor
    IMPORTING
      !textid LIKE textid OPTIONAL
      !previous LIKE previous OPTIONAL
      !mt_message TYPE if_fdt_types=>t_message OPTIONAL.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_fdt_input IMPLEMENTATION.
ENDCLASS.