CLASS cx_sy_find_infinite_loop DEFINITION
  PUBLIC
  INHERITING FROM cx_dynamic_check
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.

    CONSTANTS cx_sy_find_infinite_loop TYPE c LENGTH 32 VALUE 'F83A4F40CA347027E10000000A114BF5'. "#EC NOTEXT

    METHODS constructor
    IMPORTING
      !textid LIKE textid OPTIONAL
      !previous LIKE previous OPTIONAL.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_sy_find_infinite_loop IMPLEMENTATION.
ENDCLASS.