CLASS cx_xslt_exception DEFINITION
  PUBLIC
  INHERITING FROM cx_transformation_error
  CREATE PUBLIC.

  PUBLIC SECTION.

    CONSTANTS cx_xslt_exception TYPE c LENGTH 32 VALUE 'CAADD5A192D6D411AE7508000627B058'. "#EC NOTEXT
    CONSTANTS xslt_not_supported TYPE c LENGTH 32 VALUE '372E423ADE2DEE42E10000000A11447B'. "#EC NOTEXT

    METHODS constructor
    IMPORTING
      !textid LIKE textid OPTIONAL
      !previous LIKE previous OPTIONAL.
  PROTECTED SECTION.
ENDCLASS.

CLASS cx_xslt_exception IMPLEMENTATION.
ENDCLASS.