INTERFACE if_fdt_cp_ast_function_node
  PUBLIC.
  CONSTANTS:
    BEGIN OF gcs_ast_function,
      BEGIN OF mathematical,
        add      TYPE string VALUE 'Add',
        subtract TYPE string VALUE 'Subtract',
        multiply TYPE string VALUE 'Multiply',
        divide   TYPE string VALUE 'Divide',
      END OF mathematical,
      BEGIN OF comparison,
        isequal           TYPE string VALUE 'IsEqual',
        isnotequal        TYPE string VALUE 'IsNotEqual',
        isgreater         TYPE string VALUE 'IsGreater',
        isgreaterequal    TYPE string VALUE 'IsGreaterEqual',
        isless            TYPE string VALUE 'IsLess',
        islessequal       TYPE string VALUE 'IsLessEqual',
        isbetween         TYPE string VALUE 'In',
        isnotbetween      TYPE string VALUE 'NotIn',
        existsin          TYPE string VALUE 'ExistsIn',
        notexistsin       TYPE string VALUE 'NotExistsIn',
        matches           TYPE string VALUE 'ContainsPattern',
        notmatches        TYPE string VALUE 'NotContainsPattern',
        containsstring    TYPE string VALUE 'ContainsString',
        notcontainsstring TYPE string VALUE 'NotContainsString',
        startswith        TYPE string VALUE 'StartsWith',
        notstartswith     TYPE string VALUE 'NotStartsWith',
        endswith          TYPE string VALUE 'EndsWith',
        notendswith       TYPE string VALUE 'NotEndsWith',
        isinitial         TYPE string VALUE 'IsInitial',
        isnotinitial      TYPE string VALUE 'IsNotInitial',
      END OF comparison,
      BEGIN OF logical,
        and TYPE string VALUE 'And',
        or  TYPE string VALUE 'Or',
      END OF logical,
      BEGIN OF selection,
        top      TYPE string VALUE 'Top',
        select   TYPE string VALUE 'Select',
        sortasc  TYPE string VALUE 'SortAscending',
        sortdesc TYPE string VALUE 'SortDescending',
        filter   TYPE string VALUE 'Filter',
        first    TYPE string VALUE 'First',
      END OF selection,
      BEGIN OF aggregation,
        average       TYPE string VALUE 'Average',
        sum           TYPE string VALUE 'Sum',
        count         TYPE string VALUE 'Count',
        countdistinct TYPE string VALUE 'CountDistinct',
        min           TYPE string VALUE 'Min',
        max           TYPE string VALUE 'Max',
      END OF aggregation,
      BEGIN OF advanced,
        concatenate TYPE string VALUE 'Concat',
        round       TYPE string VALUE 'Round',
        power       TYPE string VALUE 'Power',
        today       TYPE string VALUE 'Today',
        tommorow    TYPE string VALUE 'Tomorrow',
        yesterday   TYPE string VALUE 'Yesterday',
        now         TYPE string VALUE 'Now',
      END OF advanced,
      BEGIN OF vocabulary,
        initialize TYPE string VALUE 'Initialize',
        update     TYPE string VALUE 'Update',
        append     TYPE string VALUE 'Append',
      END OF vocabulary,
      BEGIN OF range,
        rangeinclusive     TYPE string VALUE 'RangeInclusive',
        rangetoinclusive   TYPE string VALUE 'RangeToInclusive',
        rangefrominclusive TYPE string VALUE 'RangeFromInclusive',
        rangeexclusive     TYPE string VALUE 'RangeExclusive',
        array              TYPE string VALUE 'Array',
        isinnext           TYPE string VALUE 'IsInNext',
        isnotinnext        TYPE string VALUE 'IsNotInNext',
        isinlast           TYPE string VALUE 'IsInLast',
        isnotinlast        TYPE string VALUE 'IsNotInLast',
      END OF range,
      BEGIN OF time_duration_arithmetic,
        addseconds       TYPE string VALUE 'AddSeconds',
        addminutes       TYPE string VALUE 'AddMinutes',
        addhours         TYPE string VALUE 'AddHours',
        adddays          TYPE string VALUE 'AddDays',
        addweeks         TYPE string VALUE 'AddWeeks',
        addmonths        TYPE string VALUE 'AddMonths',
        addquarters      TYPE string VALUE 'AddQuarters',
        addyears         TYPE string VALUE 'AddYears',
        subtractseconds  TYPE string VALUE 'SubtractSeconds',
        subtractminutes  TYPE string VALUE 'SubtractMinutes',
        subtracthours    TYPE string VALUE 'SubtractHours',
        subtractdays     TYPE string VALUE 'SubtractDays',
        subtractweeks    TYPE string VALUE 'SubtractWeeks',
        subtractmonths   TYPE string VALUE 'SubtractMonths',
        subtractquarters TYPE string VALUE 'SubtractQuarters',
        subtractyears    TYPE string VALUE 'SubtractYears',
        secondsbetween   TYPE string VALUE 'SecondsBetween',
        minutesbetween   TYPE string VALUE 'MinutesBetween',
        hoursbetween     TYPE string VALUE 'HoursBetween',
        daysbetween      TYPE string VALUE 'DaysBetween',
        weeksbetween     TYPE string VALUE 'WeeksBetween',
        monthsbetween    TYPE string VALUE 'MonthsBetween',
        quartersbetween  TYPE string VALUE 'QuartersBetween',
        yearsbetween     TYPE string VALUE 'YearsBetween',
      END OF time_duration_arithmetic,
      parentheses TYPE string VALUE 'Parentheses',
    END OF gcs_ast_function.

  INTERFACES if_fdt_cp_ast_node.
  METHODS:
    set_function IMPORTING VALUE(iv_function) TYPE string,
    get_function RETURNING VALUE(rv_function) TYPE string,
    get_children RETURNING VALUE(rt_children) TYPE if_fdt_cp_external_types=>tt_ast_children,
    set_children IMPORTING VALUE(it_children) TYPE if_fdt_cp_external_types=>tt_ast_children.
ENDINTERFACE.