
INTERFACE if_ixml_text
  PUBLIC.

  INTERFACES if_ixml_character_data.

  ALIASES append_child
    FOR if_ixml_character_data~append_child.
  ALIASES append_data
    FOR if_ixml_character_data~append_data.
  ALIASES clone
    FOR if_ixml_character_data~clone.
  ALIASES create_filter_ancestor
    FOR if_ixml_character_data~create_filter_ancestor.
  ALIASES create_filter_and
    FOR if_ixml_character_data~create_filter_and.
  ALIASES create_filter_attribute
    FOR if_ixml_character_data~create_filter_attribute.
  ALIASES create_filter_attribute_ns
    FOR if_ixml_character_data~create_filter_attribute_ns.
  ALIASES create_filter_name
    FOR if_ixml_character_data~create_filter_name.
  ALIASES create_filter_name_ns
    FOR if_ixml_character_data~create_filter_name_ns.
  ALIASES create_filter_node_type
    FOR if_ixml_character_data~create_filter_node_type.
  ALIASES create_filter_not
    FOR if_ixml_character_data~create_filter_not.
  ALIASES create_filter_or
    FOR if_ixml_character_data~create_filter_or.
  ALIASES create_filter_parent
    FOR if_ixml_character_data~create_filter_parent.
  ALIASES create_inline_iterator
    FOR if_ixml_character_data~create_inline_iterator.
  ALIASES create_iterator
    FOR if_ixml_character_data~create_iterator.
  ALIASES create_iterator_filtered
    FOR if_ixml_character_data~create_iterator_filtered.
  ALIASES create_rev_inline_iterator
    FOR if_ixml_character_data~create_rev_inline_iterator.
  ALIASES create_rev_iterator
    FOR if_ixml_character_data~create_rev_iterator.
  ALIASES create_rev_iterator_filtered
    FOR if_ixml_character_data~create_rev_iterator_filtered.
  ALIASES delete_data
    FOR if_ixml_character_data~delete_data.
  ALIASES find_from_gid
    FOR if_ixml_character_data~find_from_gid.
  ALIASES get_attributes
    FOR if_ixml_character_data~get_attributes.
  ALIASES get_children
    FOR if_ixml_character_data~get_children.
  ALIASES get_column
    FOR if_ixml_character_data~get_column.
  ALIASES get_data
    FOR if_ixml_character_data~get_data.
  ALIASES get_depth
    FOR if_ixml_character_data~get_depth.
  ALIASES get_first_child
    FOR if_ixml_character_data~get_first_child.
  ALIASES get_gid
    FOR if_ixml_character_data~get_gid.
  ALIASES get_height
    FOR if_ixml_character_data~get_height.
  ALIASES get_last_child
    FOR if_ixml_character_data~get_last_child.
  ALIASES get_length
    FOR if_ixml_character_data~get_length.
  ALIASES get_line
    FOR if_ixml_character_data~get_line.
  ALIASES get_name
    FOR if_ixml_character_data~get_name.
  ALIASES get_namespace
    FOR if_ixml_character_data~get_namespace.
  ALIASES get_namespace_context
    FOR if_ixml_character_data~get_namespace_context.
  ALIASES get_namespace_prefix
    FOR if_ixml_character_data~get_namespace_prefix.
  ALIASES get_namespace_uri
    FOR if_ixml_character_data~get_namespace_uri.
  ALIASES get_next
    FOR if_ixml_character_data~get_next.
  ALIASES get_owner_document
    FOR if_ixml_character_data~get_owner_document.
  ALIASES get_parent
    FOR if_ixml_character_data~get_parent.
  ALIASES get_prev
    FOR if_ixml_character_data~get_prev.
  ALIASES get_root
    FOR if_ixml_character_data~get_root.
  ALIASES get_type
    FOR if_ixml_character_data~get_type.
  ALIASES get_value
    FOR if_ixml_character_data~get_value.
  ALIASES has_ancestor
    FOR if_ixml_character_data~has_ancestor.
  ALIASES insert_child
    FOR if_ixml_character_data~insert_child.
  ALIASES insert_data
    FOR if_ixml_character_data~insert_data.
  ALIASES is_leaf
    FOR if_ixml_character_data~is_leaf.
  ALIASES is_root
    FOR if_ixml_character_data~is_root.
  ALIASES normalize_data
    FOR if_ixml_character_data~normalize_data.
  ALIASES num_children
    FOR if_ixml_character_data~num_children.
  ALIASES query_interface
    FOR if_ixml_character_data~query_interface.
  ALIASES remove_child
    FOR if_ixml_character_data~remove_child.
  ALIASES remove_node
    FOR if_ixml_character_data~remove_node.
  ALIASES render
    FOR if_ixml_character_data~render.
  ALIASES replace_child
    FOR if_ixml_character_data~replace_child.
  ALIASES replace_data
    FOR if_ixml_character_data~replace_data.
  ALIASES set_data
    FOR if_ixml_character_data~set_data.
  ALIASES set_name
    FOR if_ixml_character_data~set_name.
  ALIASES set_namespace
    FOR if_ixml_character_data~set_namespace.
  ALIASES set_namespace_prefix
    FOR if_ixml_character_data~set_namespace_prefix.
  ALIASES set_namespace_uri
    FOR if_ixml_character_data~set_namespace_uri.
  ALIASES set_value
    FOR if_ixml_character_data~set_value.
  ALIASES substring_data
    FOR if_ixml_character_data~substring_data.
  ALIASES ws_only
    FOR if_ixml_character_data~ws_only.

  METHODS split_text
    IMPORTING
      !offset TYPE i
    RETURNING
      VALUE(rval) TYPE REF TO if_ixml_text.
ENDINTERFACE.