
INTERFACE if_ixml_namespace_decl
  PUBLIC.

  INTERFACES if_ixml_attribute.

  ALIASES append_child
    FOR if_ixml_attribute~append_child.
  ALIASES clone
    FOR if_ixml_attribute~clone.
  ALIASES create_filter_ancestor
    FOR if_ixml_attribute~create_filter_ancestor.
  ALIASES create_filter_and
    FOR if_ixml_attribute~create_filter_and.
  ALIASES create_filter_attribute
    FOR if_ixml_attribute~create_filter_attribute.
  ALIASES create_filter_attribute_ns
    FOR if_ixml_attribute~create_filter_attribute_ns.
  ALIASES create_filter_name
    FOR if_ixml_attribute~create_filter_name.
  ALIASES create_filter_name_ns
    FOR if_ixml_attribute~create_filter_name_ns.
  ALIASES create_filter_node_type
    FOR if_ixml_attribute~create_filter_node_type.
  ALIASES create_filter_not
    FOR if_ixml_attribute~create_filter_not.
  ALIASES create_filter_or
    FOR if_ixml_attribute~create_filter_or.
  ALIASES create_filter_parent
    FOR if_ixml_attribute~create_filter_parent.
  ALIASES create_inline_iterator
    FOR if_ixml_attribute~create_inline_iterator.
  ALIASES create_iterator
    FOR if_ixml_attribute~create_iterator.
  ALIASES create_iterator_filtered
    FOR if_ixml_attribute~create_iterator_filtered.
  ALIASES create_rev_inline_iterator
    FOR if_ixml_attribute~create_rev_inline_iterator.
  ALIASES create_rev_iterator
    FOR if_ixml_attribute~create_rev_iterator.
  ALIASES create_rev_iterator_filtered
    FOR if_ixml_attribute~create_rev_iterator_filtered.
  ALIASES find_from_gid
    FOR if_ixml_attribute~find_from_gid.
  ALIASES get_attributes
    FOR if_ixml_attribute~get_attributes.
  ALIASES get_children
    FOR if_ixml_attribute~get_children.
  ALIASES get_column
    FOR if_ixml_attribute~get_column.
  ALIASES get_depth
    FOR if_ixml_attribute~get_depth.
  ALIASES get_first_child
    FOR if_ixml_attribute~get_first_child.
  ALIASES get_gid
    FOR if_ixml_attribute~get_gid.
  ALIASES get_height
    FOR if_ixml_attribute~get_height.
  ALIASES get_last_child
    FOR if_ixml_attribute~get_last_child.
  ALIASES get_line
    FOR if_ixml_attribute~get_line.
  ALIASES get_name
    FOR if_ixml_attribute~get_name.
  ALIASES get_namespace
    FOR if_ixml_attribute~get_namespace.
  ALIASES get_namespace_context
    FOR if_ixml_attribute~get_namespace_context.
  ALIASES get_namespace_prefix
    FOR if_ixml_attribute~get_namespace_prefix.
  ALIASES get_namespace_uri
    FOR if_ixml_attribute~get_namespace_uri.
  ALIASES get_next
    FOR if_ixml_attribute~get_next.
  ALIASES get_owner_document
    FOR if_ixml_attribute~get_owner_document.
  ALIASES get_owner_element
    FOR if_ixml_attribute~get_owner_element.
  ALIASES get_parent
    FOR if_ixml_attribute~get_parent.
  ALIASES get_prev
    FOR if_ixml_attribute~get_prev.
  ALIASES get_root
    FOR if_ixml_attribute~get_root.
  ALIASES get_type
    FOR if_ixml_attribute~get_type.
  ALIASES get_value
    FOR if_ixml_attribute~get_value.
  ALIASES has_ancestor
    FOR if_ixml_attribute~has_ancestor.
  ALIASES insert_child
    FOR if_ixml_attribute~insert_child.
  ALIASES is_leaf
    FOR if_ixml_attribute~is_leaf.
  ALIASES is_root
    FOR if_ixml_attribute~is_root.
  ALIASES num_children
    FOR if_ixml_attribute~num_children.
  ALIASES query_interface
    FOR if_ixml_attribute~query_interface.
  ALIASES remove_child
    FOR if_ixml_attribute~remove_child.
  ALIASES remove_node
    FOR if_ixml_attribute~remove_node.
  ALIASES render
    FOR if_ixml_attribute~render.
  ALIASES replace_child
    FOR if_ixml_attribute~replace_child.
  ALIASES set_name
    FOR if_ixml_attribute~set_name.
  ALIASES set_namespace
    FOR if_ixml_attribute~set_namespace.
  ALIASES set_namespace_prefix
    FOR if_ixml_attribute~set_namespace_prefix.
  ALIASES set_namespace_uri
    FOR if_ixml_attribute~set_namespace_uri.
  ALIASES set_value
    FOR if_ixml_attribute~set_value.
  ALIASES specified
    FOR if_ixml_attribute~specified.
ENDINTERFACE.