INTERFACE if_web_http_header
  PUBLIC.

  CONSTANTS accept TYPE string VALUE 'Accept' ##NO_TEXT.
  CONSTANTS accept_text_html TYPE string VALUE 'text/html' ##NO_TEXT.
  CONSTANTS accept_application_xhtml TYPE string VALUE 'application/xhtml+xml' ##NO_TEXT.
  CONSTANTS accept_application_xml TYPE string VALUE 'application/xml' ##NO_TEXT.
  CONSTANTS accept_application_json TYPE string VALUE 'application/json' ##NO_TEXT.
  CONSTANTS accept_charset TYPE string VALUE 'Accept-Charset' ##NO_TEXT.
  CONSTANTS accept_charset_utf8 TYPE string VALUE 'utf-8' ##NO_TEXT.
  CONSTANTS accept_charset_iso_8859_1 TYPE string VALUE 'iso-8859-1' ##NO_TEXT.
  CONSTANTS accept_encoding TYPE string VALUE 'Accept-Encoding' ##NO_TEXT.
  CONSTANTS accept_encoding_gzip TYPE string VALUE 'gzip' ##NO_TEXT.
  CONSTANTS accept_encoding_compress TYPE string VALUE 'compress' ##NO_TEXT.
  CONSTANTS accept_encoding_deflate TYPE string VALUE 'deflate' ##NO_TEXT.
  CONSTANTS accept_language TYPE string VALUE 'Accept-Language' ##NO_TEXT.
  CONSTANTS accept_ranges TYPE string VALUE 'Accept-Ranges' ##NO_TEXT.
  CONSTANTS age TYPE string VALUE 'Age' ##NO_TEXT.
  CONSTANTS allow TYPE string VALUE 'Allow' ##NO_TEXT.
  CONSTANTS authorization TYPE string VALUE 'Authorization' ##NO_TEXT.
  CONSTANTS cache_control TYPE string VALUE 'Cache-Control' ##NO_TEXT.
  CONSTANTS connection TYPE string VALUE 'Connection' ##NO_TEXT.
  CONSTANTS content_encoding TYPE string VALUE 'Content-Encoding' ##NO_TEXT.
  CONSTANTS content_encoding_gzip TYPE string VALUE 'gzip' ##NO_TEXT.
  CONSTANTS content_encoding_compress TYPE string VALUE 'compress' ##NO_TEXT.
  CONSTANTS content_encoding_deflate TYPE string VALUE 'deflate' ##NO_TEXT.
  CONSTANTS content_language TYPE string VALUE 'Content-Language' ##NO_TEXT.
  CONSTANTS content_length TYPE string VALUE 'Content-Length' ##NO_TEXT.
  CONSTANTS content_location TYPE string VALUE 'Content-Location' ##NO_TEXT.
  CONSTANTS content_md5 TYPE string VALUE 'Content-MD5' ##NO_TEXT.
  CONSTANTS content_range TYPE string VALUE 'Content-Range' ##NO_TEXT.
  CONSTANTS content_type TYPE string VALUE 'Content-Type' ##NO_TEXT.
  CONSTANTS content_type_html_utf8 TYPE string VALUE 'text/html; charset=utf-8' ##NO_TEXT.
  CONSTANTS date TYPE string VALUE 'Date' ##NO_TEXT.
  CONSTANTS etag TYPE string VALUE 'ETag' ##NO_TEXT.
  CONSTANTS expect TYPE string VALUE 'Expect' ##NO_TEXT.
  CONSTANTS expires TYPE string VALUE 'Expires' ##NO_TEXT.
  CONSTANTS from TYPE string VALUE 'From' ##NO_TEXT.
  CONSTANTS host TYPE string VALUE 'Host' ##NO_TEXT.
  CONSTANTS if_match TYPE string VALUE 'If-Match' ##NO_TEXT.
  CONSTANTS if_modified_since TYPE string VALUE 'If-Modified-Since' ##NO_TEXT.
  CONSTANTS if_none_match TYPE string VALUE 'If-None-Match' ##NO_TEXT.
  CONSTANTS if_range TYPE string VALUE 'If-Range' ##NO_TEXT.
  CONSTANTS if_unmodified_since TYPE string VALUE 'If-Unmodified-Since' ##NO_TEXT.
  CONSTANTS last_modified TYPE string VALUE 'Last-Modified' ##NO_TEXT.
  CONSTANTS location TYPE string VALUE 'Location' ##NO_TEXT.
  CONSTANTS max_forwards TYPE string VALUE 'Max-Forwards' ##NO_TEXT.
  CONSTANTS pragma TYPE string VALUE 'Pragma' ##NO_TEXT.
  CONSTANTS proxy_authenticate TYPE string VALUE 'Proxy-Authenticate' ##NO_TEXT.
  CONSTANTS proxy_authorization TYPE string VALUE 'Proxy-Authorization' ##NO_TEXT.
  CONSTANTS range TYPE string VALUE 'Range' ##NO_TEXT.
  CONSTANTS referer TYPE string VALUE 'Referer' ##NO_TEXT.
  CONSTANTS retry_after TYPE string VALUE 'Retry-After' ##NO_TEXT.
  CONSTANTS server TYPE string VALUE 'Server' ##NO_TEXT.
  CONSTANTS te TYPE string VALUE 'TE' ##NO_TEXT.
  CONSTANTS trailer TYPE string VALUE 'Trailer' ##NO_TEXT.
  CONSTANTS transfer_encoding TYPE string VALUE 'Transfer-Encoding' ##NO_TEXT.
  CONSTANTS upgrade TYPE string VALUE 'Upgrade' ##NO_TEXT.
  CONSTANTS user_agent TYPE string VALUE 'User-Agent' ##NO_TEXT.
  CONSTANTS vary TYPE string VALUE 'Vary' ##NO_TEXT.
  CONSTANTS via TYPE string VALUE 'Via' ##NO_TEXT.
  CONSTANTS warning TYPE string VALUE 'Warning' ##NO_TEXT.
  CONSTANTS www_authenticate TYPE string VALUE 'WWW-Authenticate' ##NO_TEXT.
  CONSTANTS content_disposition TYPE string VALUE 'Content-Disposition' ##NO_TEXT.
  CONSTANTS content_transfer_encoding TYPE string VALUE 'Content-Transfer-Encoding' ##NO_TEXT.
  CONSTANTS x_requested_with TYPE string VALUE 'X-Requested-With' ##NO_TEXT.
  CONSTANTS xmlhttprequest TYPE string VALUE 'XMLHttpRequest' ##NO_TEXT.
  CONSTANTS x_xhr_logon TYPE string VALUE 'X-XHR-Logon' ##NO_TEXT.
ENDINTERFACE.