
INTERFACE if_wsprotocol
  PUBLIC.

  CONSTANTS async_messaging TYPE string VALUE 'IF_WSPROTOCOL_ASYNC_MESSAGING' ##NO_TEXT.
  CONSTANTS routing TYPE string VALUE 'IF_WSPROTOCOL_ROUTING' ##NO_TEXT.
  CONSTANTS attachments TYPE string VALUE 'IF_WSPROTOCOL_ATTACHMENTS' ##NO_TEXT.
  CONSTANTS xi_header TYPE string VALUE 'IF_WSPROTOCOL_XI_HEADER' ##NO_TEXT.
  CONSTANTS ws_header TYPE string VALUE 'IF_WSPROTOCOL_WS_HEADER' ##NO_TEXT.
  CONSTANTS payload TYPE string VALUE 'IF_WSPROTOCOL_PAYLOAD' ##NO_TEXT.
  CONSTANTS message_id TYPE string VALUE 'IF_WSPROTOCOL_MESSAGE_ID' ##NO_TEXT.
  CONSTANTS session TYPE string VALUE 'IF_WSPROTOCOL_SESSION' ##NO_TEXT.
  CONSTANTS sequence TYPE string VALUE 'IF_WSPROTOCOL_SEQUENCE' ##NO_TEXT.
  CONSTANTS sap_addressing TYPE string VALUE 'IF_WSPROTOCOL_SAP_ADDRESSING' ##NO_TEXT.
  CONSTANTS luw_control TYPE string VALUE 'IF_WSPROTOCOL_LUW_CONTROL' ##NO_TEXT.
  CONSTANTS connectivity TYPE string VALUE 'IF_WSPROTOCOL_CONNECTIVITY' ##NO_TEXT.
  CONSTANTS ibc TYPE string VALUE 'IF_WSPROTOCOL_IBC' ##NO_TEXT.
  CONSTANTS transport TYPE string VALUE 'IF_WSPROTOCOL_TRANSPORT' ##NO_TEXT.
ENDINTERFACE.