CLASS xco_cp_message DEFINITION PUBLIC FINAL CREATE PRIVATE.
  PUBLIC SECTION.
    CLASS-DATA:
      type TYPE REF TO cl_xco_cp_message_type_f READ-ONLY.

ENDCLASS.

CLASS xco_cp_message IMPLEMENTATION.
ENDCLASS.