CLASS xco_cp_name DEFINITION PUBLIC FINAL CREATE PRIVATE.
  PUBLIC SECTION.
    CLASS-DATA:
      choice TYPE REF TO if_xco_cp_name_choice_factory READ-ONLY.

ENDCLASS.

CLASS xco_cp_name IMPLEMENTATION.
ENDCLASS.