CLASS xco_cp_language DEFINITION PUBLIC FINAL CREATE PRIVATE.
  PUBLIC SECTION.
    CLASS-DATA:
      format TYPE REF TO if_xco_cp_lang_format_factory READ-ONLY.

ENDCLASS.

CLASS xco_cp_language IMPLEMENTATION.
ENDCLASS.